### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by mrichman** [robperc/FinderSidebarEditor#2]
Using Python 3.7:

```
$ python tests.py
Traceback (most recent call last):
  File "tests.py", line 1, in <module>
    from FinderSidebarEditor import FinderSidebar
  File "/User/Mark/github/robperc/FinderSidebarEditor/FinderSidebarEditor.py", line 23, in <module>
    loadBundleFunctions(SFL_bundle, globals(), functions)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jberkner** [comment]
I ran into this as well. Python 3 has some type of change around strings not being binaries. The fix is to tell python the string is bytes by adding the 'b':
`
functions  = [('LSSharedFileListCreate',              b'^{OpaqueLSSharedFileListRef=}^{__CFAllocator=}^{__CFString=}@'),
				('LSSharedFileListCopySnapshot',        b'^{__CFArray=}^{OpaqueLSSharedFileListRef=}o^I'),
				('LSSharedFileListItemCopyDisplayName', b'^{__CFString=}^{OpaqueLSSharedFileListItemRef=}'),
				('LSSharedFileListItemResolve',         b'i^{OpaqueLSSharedFileListItemRef=}Io^^{__CFURL=}o^{FSRef=[80C]}'),
				('LSSharedFileListItemMove',            b'i^{OpaqueLSSharedFileListRef=}^{OpaqueLSSharedFileListItemRef=}^{OpaqueLSSharedFileListItemRef=}'),
				('LSSharedFileListItemRemove',          b'i^{OpaqueLSSharedFileListRef=}^{OpaqueLSSharedFileListItemRef=}'),
				('LSSharedFileListRemoveAllItems',      b'i^{OpaqueLSSharedFileListRef=}'),
				('LSSharedFileListInsertItemURL',       b'^{OpaqueLSSharedFileListItemRef=}^{OpaqueLSSharedFileListRef=}^{OpaqueLSSharedFileListItemRef=}^{__CFString=}^{OpaqueIconRef=}^{__CFURL=}^{__CFDictionary=}^{__CFArray=}'),
				('kLSSharedFileListItemBeforeFirst',    b'^{OpaqueLSSharedFileListItemRef=}'),]
	loadBundleFunctions(SFL_bundle, globals(), functions)
`

and lower in the code
`
loadBundleFunctions(NetFS_bundle, NetFS, [('NetFSMountURLSync', b'i@@@@@@o^@')])
`

**Comment by robperc** [comment]
This should be fixed in the latest PR that was just merged.

https://github.com/robperc/FinderSidebarEditor/pull/4
